### ISSUE TITLE
desktop screenshot

### ISSUE THREAD

**Issue by ashwin31** [Ali1Ammar/screenshot_modes#1]
Can I take whole desktop screenshot with this package?

**Comment by Ali1Ammar** [comment]
we use device preview(device frame) packages for handling the frame and screen size 
you could use any size and frame available within this package 
see this link there is a example of laptop and desktop configuration 
https://pub.dev/packages/device_frame

 
if you want to build app for taking screenshot of the computer screen you could use win32 package i think there is screenshot.dart example in it

**Comment by ashwin31** [comment]
Hi @Ali1Ammar 

Thank you for the direction. I saw win32 but I need to take desktop screenshot in linux, mac, and windows. Can you suggest any package that support linux and mac?

**Comment by Ali1Ammar** [comment]
@ashwin31 for linux you could  try   ImageMagick 
and i think it may work on other platform also see
https://imagemagick.org/script/import.php
you could call it from dart code using Process.run

**Comment by ashwin31** [comment]
Thank you @Ali1Ammar
